# Generated by Django 3.2.13 on 2022-05-17 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_login', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentmodel',
            name='section',
            field=models.CharField(choices=[('Select One', 'Select One'), ('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], default='Select One', max_length=10),
        ),
    ]
