# Generated by Django 3.2.13 on 2022-07-14 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_login', '0002_studentmodel_section'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentmodel',
            name='joining_date',
            field=models.DateField(auto_now=True),
        ),
    ]
