# Generated by Django 3.2.13 on 2022-07-17 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_login', '0003_alter_studentmodel_joining_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teachermodel',
            name='designation',
            field=models.CharField(choices=[('Lecturer - Permanent', 'Lecturer - Permanent'), ('Lecturer - Guest', 'Lecturer - Guest'), ('Lecturer & Department-Head', 'Lecturer & Department-Head'), ('Assistant-Lecturer', 'Assistant-Lecturer')], max_length=50),
        ),
    ]
