# Generated by Django 3.2.13 on 2022-05-15 12:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('App_login', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssignmentModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(choices=[('cse', 'CSE'), ('bba', 'BBA'), ('bthm', 'BTHM')], max_length=50)),
                ('batch', models.CharField(max_length=50)),
                ('semester', models.CharField(max_length=50)),
                ('subject', models.CharField(choices=[('Introduction To Computer', 'Introduction To Computer'), ('Programming Language', 'Programming Language')], max_length=100)),
                ('Title', models.CharField(max_length=500)),
                ('assignment', models.FileField(upload_to='assignments/')),
                ('created', models.DateField(auto_now=True)),
                ('deadline', models.DateField()),
                ('status', models.BooleanField(default=True)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_provider', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AssignmentSubmissionModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submission_file', models.FileField(upload_to='submitted_assignments/')),
                ('created', models.DateField(auto_now=True)),
                ('status', models.BooleanField(default=False)),
                ('my_assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='my_assignment', to='App_main.assignmentmodel')),
                ('submitted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_submit', to='App_login.studentmodel')),
            ],
        ),
    ]
