# Generated by Django 3.2.13 on 2022-05-15 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_main', '0002_auto_20220515_1854'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignmentsubmissionmodel',
            name='submission_file',
            field=models.FileField(blank=True, upload_to='submitted_assignments/'),
        ),
    ]
