# Generated by Django 3.2.13 on 2022-05-17 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_main', '0004_auto_20220517_2044'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignmentsubmissionmodel',
            name='marks',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
