# Generated by Django 3.2.13 on 2022-05-23 19:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App_login', '0002_studentmodel_section'),
        ('App_main', '0005_assignmentsubmissionmodel_marks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignmentmodel',
            name='subject',
            field=models.CharField(choices=[('Introduction To Computer', 'Introduction To Computer'), ('Programming Language', 'Programming Language'), ('Web Engineering', 'Web Engineering'), ('Image Processing', 'Image Processing')], max_length=100),
        ),
        migrations.CreateModel(
            name='AttendanceModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(choices=[('cse', 'CSE'), ('bba', 'BBA'), ('bthm', 'BTHM')], max_length=50)),
                ('batch', models.CharField(choices=[('Select One', 'Select One'), ('17th', '17th'), ('18th', '18th'), ('19th', '19th'), ('20th', '20th'), ('21st', '21st'), ('22nd', '22nd'), ('23rd', '23rd'), ('24th', '24th'), ('25th', '25th'), ('26th', '26th'), ('27th', '27th')], max_length=50)),
                ('section', models.CharField(choices=[('Select One', 'Select One'), ('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], max_length=10)),
                ('semester', models.CharField(choices=[('Select One', 'Select One'), ('1st', '1st'), ('2nd', '2nd'), ('3rd', '3rd'), ('4th', '4th'), ('5th', '5th'), ('6th', '6th'), ('7th', '7th'), ('8th', '8th')], max_length=50)),
                ('subject', models.CharField(choices=[('Introduction To Computer', 'Introduction To Computer'), ('Programming Language', 'Programming Language'), ('Web Engineering', 'Web Engineering'), ('Image Processing', 'Image Processing')], max_length=100)),
                ('status', models.BooleanField(blank=True, default=False)),
                ('date', models.DateField(auto_now=True)),
                ('student', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='student_attendance', to='App_login.studentmodel')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='course_teacher', to='App_login.teachermodel')),
            ],
        ),
    ]
