# Generated by Django 3.2.13 on 2022-05-27 04:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('App_login', '0002_studentmodel_section'),
        ('App_main', '0006_auto_20220524_0148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignmentmodel',
            name='batch',
            field=models.CharField(choices=[('Select One', 'Select One'), ('16th', '16th'), ('17th', '17th'), ('18th', '18th'), ('19th', '19th'), ('20th', '20th'), ('21st', '21st'), ('22nd', '22nd'), ('23rd', '23rd'), ('24th', '24th'), ('25th', '25th'), ('26th', '26th'), ('27th', '27th')], max_length=50),
        ),
        migrations.AlterField(
            model_name='attendancemodel',
            name='batch',
            field=models.CharField(choices=[('Select One', 'Select One'), ('16th', '16th'), ('17th', '17th'), ('18th', '18th'), ('19th', '19th'), ('20th', '20th'), ('21st', '21st'), ('22nd', '22nd'), ('23rd', '23rd'), ('24th', '24th'), ('25th', '25th'), ('26th', '26th'), ('27th', '27th')], max_length=50),
        ),
        migrations.CreateModel(
            name='TestSubmissionModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submission_file', models.FileField(blank=True, upload_to='submitted_tests/')),
                ('created', models.DateField(auto_now=True)),
                ('marks', models.PositiveIntegerField(default=0)),
                ('status', models.BooleanField(default=False)),
                ('my_test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='my_test', to='App_main.assignmentmodel')),
                ('submitted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_submit_student', to='App_login.studentmodel')),
            ],
        ),
        migrations.CreateModel(
            name='TestModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(choices=[('cse', 'CSE'), ('bba', 'BBA'), ('bthm', 'BTHM')], max_length=50)),
                ('batch', models.CharField(choices=[('Select One', 'Select One'), ('16th', '16th'), ('17th', '17th'), ('18th', '18th'), ('19th', '19th'), ('20th', '20th'), ('21st', '21st'), ('22nd', '22nd'), ('23rd', '23rd'), ('24th', '24th'), ('25th', '25th'), ('26th', '26th'), ('27th', '27th')], max_length=50)),
                ('section', models.CharField(choices=[('Select One', 'Select One'), ('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], default='Select One', max_length=10)),
                ('semester', models.CharField(choices=[('Select One', 'Select One'), ('1st', '1st'), ('2nd', '2nd'), ('3rd', '3rd'), ('4th', '4th'), ('5th', '5th'), ('6th', '6th'), ('7th', '7th'), ('8th', '8th')], max_length=50)),
                ('subject', models.CharField(choices=[('Introduction To Computer', 'Introduction To Computer'), ('Programming Language', 'Programming Language'), ('Web Engineering', 'Web Engineering'), ('Image Processing', 'Image Processing')], max_length=100)),
                ('Title', models.CharField(max_length=500)),
                ('test_paper', models.FileField(upload_to='test_papers/')),
                ('created', models.DateField(auto_now=True)),
                ('starting_time', models.DateTimeField()),
                ('deadline', models.DateTimeField()),
                ('status', models.BooleanField(default=True)),
                ('total_marks', models.PositiveIntegerField(default=0)),
                ('test_provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_holder', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
