# Generated by Django 3.2.13 on 2022-05-27 12:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App_main', '0007_auto_20220527_1053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testmodel',
            name='created',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='testsubmissionmodel',
            name='created',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='testsubmissionmodel',
            name='my_test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='my_test', to='App_main.testmodel'),
        ),
    ]
