# Generated by Django 3.2.13 on 2022-07-06 06:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('App_main', '0008_auto_20220527_1815'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoutineModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(choices=[('cse', 'CSE'), ('bba', 'BBA'), ('bthm', 'BTHM')], max_length=50)),
                ('batch', models.CharField(choices=[('Select One', 'Select One'), ('16th', '16th'), ('17th', '17th'), ('18th', '18th'), ('19th', '19th'), ('20th', '20th'), ('21st', '21st'), ('22nd', '22nd'), ('23rd', '23rd'), ('24th', '24th'), ('25th', '25th'), ('26th', '26th'), ('27th', '27th')], max_length=50)),
                ('section', models.CharField(choices=[('Select One', 'Select One'), ('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], default='Select One', max_length=10)),
                ('semester', models.CharField(choices=[('Select One', 'Select One'), ('1st', '1st'), ('2nd', '2nd'), ('3rd', '3rd'), ('4th', '4th'), ('5th', '5th'), ('6th', '6th'), ('7th', '7th'), ('8th', '8th')], max_length=50)),
                ('routine', models.FileField(upload_to='routines')),
                ('created', models.DateTimeField(auto_now=True)),
                ('status', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routine_provider', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
