# Generated by Django 3.2.13 on 2022-07-06 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_main', '0010_noticemodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='noticemodel',
            name='title',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
