# Generated by Django 3.2.13 on 2022-07-14 20:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App_login', '0003_alter_studentmodel_joining_date'),
        ('App_main', '0012_providesalarymodel_salarymodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentFeesModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tuition_fee', models.PositiveIntegerField()),
                ('semester_fee', models.PositiveIntegerField()),
                ('fee_counter', models.PositiveIntegerField(default=0)),
                ('semester_counter', models.PositiveIntegerField(default=0)),
                ('created', models.DateTimeField(auto_now=True)),
                ('status', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student', to='App_login.studentmodel')),
            ],
        ),
        migrations.CreateModel(
            name='SemesterFeeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now=True)),
                ('status', models.BooleanField(default=False)),
                ('fee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fee_semester', to='App_main.studentfeesmodel')),
            ],
        ),
        migrations.CreateModel(
            name='MonthlyFeeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now=True)),
                ('status', models.BooleanField(default=False)),
                ('fee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fee_monthly', to='App_main.studentfeesmodel')),
            ],
        ),
    ]
