# Generated by Django 3.2.13 on 2022-07-17 02:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App_login', '0004_alter_teachermodel_designation'),
        ('App_main', '0013_monthlyfeemodel_semesterfeemodel_studentfeesmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookLocationModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('self_no', models.CharField(max_length=255)),
                ('row_no', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='BookModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True)),
                ('cover', models.ImageField(upload_to='book_cover')),
                ('author', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True, max_length=25000, null=True)),
                ('available', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='CategoryModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='BorrowModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('date', models.DateField(auto_now=True)),
                ('status', models.BooleanField(default=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App_main.bookmodel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='borrower', to='App_login.studentmodel')),
            ],
        ),
        migrations.AddField(
            model_name='bookmodel',
            name='categories',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App_main.categorymodel'),
        ),
        migrations.AddField(
            model_name='bookmodel',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book_location', to='App_main.booklocationmodel'),
        ),
    ]
